definitions:
  handler.request:
    properties:
      codigo:
        type: string
      color:
        type: string
      fecha_creacion:
        type: string
      nombre:
        type: string
      precio:
        type: integer
      publicado:
        type: boolean
      stock:
        type: integer
    type: object
  web.Response:
    properties:
      code:
        type: integer
      data: {}
      error:
        type: string
    type: object
info:
  contact:
    name: API Support
    url: https://developers.mercadolibre.com.ar/support
  description: Product management CRUD
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://developers.mercadolibre.com.ar/es_ar/terminos-y-condiciones
  title: MELI Camilo Calder√≥n API
  version: "1.0"
paths:
  /productos:
    get:
      consumes:
      - application/json
      description: Get all products or filter by defining its keys in URL
      parameters:
      - description: Authorization token
        in: header
        name: token
        type: string
      - description: Filter by name
        in: query
        name: nombre
        type: string
      - description: Filter by color
        in: query
        name: color
        type: string
      - description: Filter by price
        in: query
        name: precio
        type: string
      - description: Filter by stock
        in: query
        name: stock
        type: string
      - description: Filter by code
        in: query
        name: codigo
        type: string
      - description: Filter by published
        in: query
        name: publicado
        type: string
      - description: Filter by creation date
        in: query
        name: fecha_creacion
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: List and filter products
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Store products
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product to store
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Store product
      tags:
      - Products
  /productos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete product by a given ID
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
      summary: Delete product
      tags:
      - Products
    get:
      consumes:
      - application/json
      description: Get a single product by a given ID
      parameters:
      - description: Authorization token
        in: header
        name: token
        required: true
        type: string
      - description: Filter by ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Get product by ID
      tags:
      - Products
    patch:
      consumes:
      - application/json
      description: Update product name and price by a given ID
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product name and price to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      - description: ID to update
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update product name and price
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Update product by a given ID
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: Product to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/handler.request'
      - description: ID to update
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/web.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.Response'
      summary: Update product
      tags:
      - Products
swagger: "2.0"
